name: Build and deploy ASP.Net Core app to Azure Web App
on:
  push:
    branches:
      - dev-athlete
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      PROJECT_NAME: 'OlympicMedalistBoard'

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "${{ runner.tool_cache }}/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore ./${{env.PROJECT_NAME}}.sln

      - name: Build with dotnet
        run: dotnet build ./${{env.PROJECT_NAME}}.sln --configuration Release

      - name: Apply migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: dotnet ef database update --startup-project ./OlympicMedalistBoard/OlympicMedalistBoard.csproj --project ./OlympicMedalistBoard.DAL/OlympicMedalistBoard.DAL.csproj

      - name: dotnet publish
        run: dotnet publish ./${{env.PROJECT_NAME}}.sln -c Release -o "${{runner.temp}}/${{env.PROJECT_NAME}}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{runner.temp}}/${{env.PROJECT_NAME}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24E719864B934BA5A3CFA0C63FAD2ABA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_15F59B4F7FE94B44BBA83D64797E47FF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67C66AE3747F466EACE799C20E2F9777 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.PROJECT_NAME}}
          slot-name: 'Production'
          package: .